[package]
name = "clunker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit="0.28.2"
windows="0.44.0"


[build-dependencies]
bindgen="0.64.0"

